config/routes.rb
Learnmaze::Application.routes.draw do

  get "select_community/index"

  resources :departments

  resources :memberships, only: [:create, :destroy]

   resources :comments
  resources :communities

  get "search/search"
  post "search/search"

  match 'search/search' => 'search#search', :as => :search_search

  get "profile/view"

  get "specs/index"

  get "specs/edit"
  post "specs/edit"

  get "home/index"

  get "home/show"

  authenticated :user do

    root :to => "profile#view"
  end

  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" ,:registrations => "registrations"}

  devise_scope :user do

  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'

  end

  resources :user do
    member do
      get 'image'
    end
  end

  match "profile/:id" => "profile#show"

  get "friendship/req"
  post "friendship/req"

  get "friendship/accept"
  get "friendship/reject"

  resources :microposts do
    resources :comments
  end

  resources :feed_entries do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]

  get "external/index"
  get "external/linkedin"
  post "/external" => "external#create"

   root :to => 'home#index'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
      <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>
<% end %>

app/views/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end -%>
<% end -%>

app/views/shared/_personal_edit.html.erb
<%=  form_for :spec , :html => {:multipart => true} do |form|  %>

    <fieldset>
      <legend><%= @title %> </legend>

      <div class="form_row">
        <%= form.label 'first_name:' %>
        <%= form.text_field :first_name,:size =>40 %>
      </div>


      <div class="form_row">
        <%= form.label 'last_name:' %>
        <%= form.text_field :last_name,:size =>40 %>
      </div>

      <div class ="form_row">
        <%= radio_button :spec, :gender,"Male" %> Male
        <%= radio_button :spec, :gender,"Female" %> Female
      </div>

      <div class ="form_row">
        <label for =" birthday">Birthdate:</label>
        <%= date_select :spec, :birthdate,
                        :start_year => Spec::START_YEAR,
                        :end_year => Time.now.year,
                        :include_blank => true,
                        :order => [:day,:month,:year] %>
      </div>


      <div class="form_row">
        <%= form.label 'College' %>
        <%= form.text_field :college,:size =>40 %>
      </div>

      <div class="form_row">
        <%= form.label 'Image upload' %>
        <%= form.file_field :image %>
      </div>


      <%=submit_tag "Update",:class => "submit"%>

    </fieldset>

<%end%>

app/views/shared/_sign_in.html.erb
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <div id="sign_in_email"><%= f.label :email %>
      <%= f.email_field :email, :autofocus => true %></div>

    <div id="sign_in_password" ><%= f.label :password %>
      <%= f.password_field :password %></div>

    <% if devise_mapping.rememberable? -%>
        <div id="sign_in_checkbox"><%= f.check_box :remember_me %><div id="remember"> <%= f.label :remember_me %></div></div>
    <% end -%>

    <div id="sign_in"><%= f.submit "Sign in" %></div>


    <div id="sign_in_forget">
    <%= link_to "Forgot your password?", new_password_path(resource_name) %>
    </div>


<% end %>

app/views/shared/_sign_up.html.erb
<h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>

    <div><%= f.label :email %><br />
      <%= f.email_field :email, :autofocus => true %></div>

    <div><%= f.label :password %><br />
      <%= f.password_field :password %></div>

    <div><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %></div>

    <div class="field">
      <%= f.label :department_tokens,"Departmentssss"%></br>
      <%= f.text_field :department_tokens %>
    </div>


    <div><%= f.submit "Sign up" %></div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>