config/routes.rb
Learnmaze::Application.routes.draw do

  get "select_community/index"

  resources :departments

  resources :memberships, only: [:create, :destroy]

   resources :comments
  resources :communities

  get "search/search"
  post "search/search"

  match 'search/search' => 'search#search', :as => :search_search

  get "profile/view"

  get "specs/index"

  get "specs/edit"
  post "specs/edit"

  get "home/index"

  get "home/show"

  authenticated :user do

    root :to => "profile#view"
  end

  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" ,:registrations => "registrations"}

  devise_scope :user do

  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'

  end

  resources :user do
    member do
      get 'image'
    end
  end

  match "profile/:id" => "profile#show"

  get "friendship/req"
  post "friendship/req"

  get "friendship/accept"
  get "friendship/reject"

  resources :microposts do
    resources :comments
  end

  resources :feed_entries do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]

  get "external/index"
  get "external/linkedin"
  post "/external" => "external#create"

   root :to => 'home#index'

end

app/models/community.rb
class Community < ActiveRecord::Base
  attr_accessible :name,:community_image,:remote_community_image_url,:department_tokens

  has_many :memberships
  has_many :users, :through => :memberships

  has_many :departmentships
  has_many :departments, :through => :departmentships

 mount_uploader :community_image,CommunityImageUploader
  attr_reader :department_tokens

  def department_tokens=(ids)
    self.department_ids = ids.split(",")
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @communities }
    end
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    @community = Community.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @community }
    end
  end

  # GET /communities/new
  # GET /communities/new.json
  def new
    @community = Community.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @community }
    end
  end

  # GET /communities/1/edit
  def edit
    @community = Community.find(params[:id])
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(params[:community])

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render json: @community, status: :created, location: @community }
      else
        format.html { render action: "new" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /communities/1
  # PUT /communities/1.json
  def update
    @community = Community.find(params[:id])

    respond_to do |format|
      if @community.update_attributes(params[:community])
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community = Community.find(params[:id])
    @community.destroy

    respond_to do |format|
      format.html { redirect_to communities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_for(@community) do |f| %>
  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% @community.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class ="field">
    <%= f.label :Description %>
    <%= f.text_area :name ,size:"25x2" %>
  </div>

    <div class="form_row">
      <%= f.label 'Image upload' %>
      <%= f.file_field :community_image %>
    </div>

    <div class="field">
      <%= f.label :department_tokens,"Departmentssss"%></br>
      <%= f.text_field :department_tokens %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing community</h1>

<%= render 'form' %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<h1>Listing communities</h1>



<% @communities.each do |community| %>


    <div class="painting">
      <div class="name">
        <%= community.name %>
      </div>


        <% if community.community_image? %>
        <%=image_tag community.community_image_url(:thumb).to_s %>
        <% else %>
          <div class="image_placeholder">
          </div>
        <% end %>


      <div class="actions">
        <%= link_to 'Show', community %>
        <%= link_to 'Edit', edit_community_path(community) %>
        <%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %>

        <% if current_user.joined?(community) %>
            <%= form_for(current_user.memberships.find_by_community_id(community),
                         html: { method: :delete }) do |f| %>
                <%= f.submit "Unjoin", class: "btn btn-primary" %>
            <% end %>

        <% else %>
            <%= form_for current_user.memberships.build(community_id:community.id) do |f| %>
                <div><%= f.hidden_field :community_id %></div>
                <%= f.submit "Join", class: "btn btn-primary" %>
            <% end %>

        <% end %>



      </div>
    </div>




<% end %>


<br />

<%= link_to 'New Community', new_community_path %>

app/views/communities/new.html.erb
<h1>New community</h1>

<%= render 'form' %>

<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<div class="span3">

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @community.name %>
</p>


<%= link_to 'Edit', edit_community_path(@community) %> |
<%= link_to 'Back', communities_path %>
</div>

<div class="span7">
    Posts
</div>


<div class="painting">
  <div class="name">
     Hello world
  </div>

  <div class="image_placeholder">
        as
  </div>

  <div class="actions">
    asd
  </div>
</div>


<div class="span2">
<% if current_user.joined?(@community) %>
    <%= form_for(current_user.memberships.find_by_community_id(@community),
                 html: { method: :delete }) do |f| %>
        <%= f.submit "Unjoin", class: "btn btn-primary" %>
    <% end %>

<% else %>
    <%= form_for current_user.memberships.build(community_id:@community.id) do |f| %>
        <div><%= f.hidden_field :community_id %></div>
        <%= f.submit "Join", class: "btn btn-primary" %>
    <% end %>

<% end %>
</div>