config/routes.rb
Learnmaze::Application.routes.draw do

  get "select_community/index"

  resources :departments

  resources :memberships, only: [:create, :destroy]

   resources :comments
  resources :communities

  get "search/search"
  post "search/search"

  match 'search/search' => 'search#search', :as => :search_search

  get "profile/view"

  get "specs/index"

  get "specs/edit"
  post "specs/edit"

  get "home/index"

  get "home/show"

  authenticated :user do

    root :to => "profile#view"
  end

  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" ,:registrations => "registrations"}

  devise_scope :user do

  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'

  end

  resources :user do
    member do
      get 'image'
    end
  end

  match "profile/:id" => "profile#show"

  get "friendship/req"
  post "friendship/req"

  get "friendship/accept"
  get "friendship/reject"

  resources :microposts do
    resources :comments
  end

  resources :feed_entries do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]

  get "external/index"
  get "external/linkedin"
  post "/external" => "external#create"

   root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learnmaze" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->


    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag "LM.png", :rel => 'shortcut icon' %>
  </head>
  <body>




    <div class="nav nav-tabs">



          <% unless user_signed_in?  %>

          <a class="brand" href="<%= root_url %>"><%= image_tag "LearnMaze.png" %></a>

            <div class="login">
              <%= render "shared/sign_in" %>
            </div>


          <% end %>



              <% if user_signed_in? %>

                  <div class="navbar">
                    <div class="navbar-inner">
                      <div class="container">

                        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </a>




                        <!-- Everything you want hidden at 940px or less, place within here -->
                        <div class="nav-collapse collapse">
                          <!-- .nav, .navbar-search, .navbar-form, etc -->
                           <ul class="nav">
                          <!-- Be sure to leave the brand out there if you want it shown -->
                          <li><%= link_to "Learn Maze", root_url, :class => "brand" %></li>

                          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>

                          <li><%= link_to('Account Settings', edit_user_registration_path) %>  </li>

                          <%= form_tag search_search_path, :method => :get ,:class =>"navbar-search pull-left" do %>
                              <p >
                                <%= text_field_tag :search, params[:search], {:size => 40, :class => "search-query" }%>
                                <%= submit_tag 'Search' , :name => nil %>
                              </p>
                          <% end %>

                          <li> <%= link_to "Home", "/profile/view" %></li>

                          <li><%= link_to "Materials", root_url %></li>

                          <li><%= link_to "Notifications",root_url %></li>

                           </ul>

                        </div>

                      </div>
                    </div>
                  </div>






              <% else %>


              <% end %>



          </div>



    <div class="container-fluid">
      <div class="row-fluid">


          <%= bootstrap_flash %>
          <%= yield %>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js" %>

    <%= javascript_include_tag "application"%>



  </body>
</html>